[package]
name = "trotcast"
version = "0.0.2"
authors = ["dsgallups <dsgallups@protonmail.com>"]
repository = "https://github.com/dsgallups/trotcast"
description = "PARKED mpmc broadcast impl"
license = "MIT or Apache-2.0"
documentation = "https://docs.rs/trotcast"
readme = "README.md"
edition = "2024"

[dependencies]
tracing = "0.1.41"
tracing-subscriber = "0.3.20"

[dev-dependencies]
crossbeam-channel = "0.5.15"
