[package]
name = "trotcast"
version = "0.0.1"
authors = ["dsgallups <dsgallups@protonmail.com>"]
repository = "https://github.com/dsgallups/trotcast"
description = "PARKED mpmc broadcast impl"
license = "MIT or Apache-2.0"
documentation = "https://docs.rs/robo-rs"
readme = "README.md"
edition = "2024"

[dependencies]
