[package]
name = "trotcast"
version = "0.0.0"
authors = ["dsgallups <dsgallups@protonmail.com>"]
repository = "https://github.com/dsgallups/robo-rs"
description = "PARKED High-level robotics library to bootstrap rust projects"
license = "MIT or Apache-2.0"
documentation = "https://docs.rs/robo-rs"
readme = "README.md"
edition = "2024"

[dependencies]
